create table roasts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  nickname text not null,
  score int not null,
  roast_text text not null,
  analysis text not null, -- Detailed breakdown
  verdict text not null
);
